sudo: required
services:
  - docker
     

before_install:
  -docker buid -t adityayadav/docker-react  -fDockeefile.dev .
 	

script:
   -docker run adityayadav/docker-react npm run test -- --coverage
 