sudo: required
services:
  - docker
     

before_install:
   - docker build -t adityayadav/docker-react -f Dockerfile.dev .
 	

script:
   - docker run -e CI=true adityayadav/docker-react npm run test

langauge: grneric
 
