sudo: required
services:
  - docker
     

before_install:
   - docker build -t adityayadav/docker-react -f Dockerfile.dev .
script:
   - docker run -e CI=true adityayadav/docker-react npm run test

langauge: grneric
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-744976051710"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
 
